### ISSUE TITLE
train.py runs with error 

### ISSUE THREAD

**Issue by 5hevchenko** [Trailblazer97/Text-classification#1]
Traceback (most recent call last):
  File "predict.py", line 49, in <module>
    output_class.append(list(indexed_type.keys())[list(indexed_type.values()).index(i)])
NameError: name 'indexed_type' is not defined

**Comment by yashbarapatre** [comment]
@5hevchenko The error has been successfully taken care of. I have now created a dump of the variable 'indexed_type' in train.py and retrieved it in predict.py. That'll solve your issue. The dump has also been uploaded.
